# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(nickname: 'けんたろう', content: '初めまして。健太郎と申します。洋服が大好きで、友達にコーディネートするのが得意です。私のアドバイスで、違った自分を発見してください！'　birthday: '1998-12-10', age: '２０代', gender: '男', email: 'kentaro@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111111)
User.create(nickname: 'けんじ', content: 'こんにちは＾＾着こなしがわからない人は結局自分がわかっていないのと同じです。着こなしを理解して、自分をもっと理解しましょう。', birthday: '1985-12-10', age: '3０代', gender: '男', email: 'kenji@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111112)
User.create(nickname: 'かな', content: '学生時代の夢は、有名雑誌のスタイリストになる事でした。友達からも、かなのアドバイスが的確で嬉しいとよく言われます。皆さんのお役に立ちたいです。', birthday: '1998-12-10', age: '２０代', gender: '女', email: 'kana@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111113)
User.create(nickname: 'みき', content: 'レジャーが大好きで、仕事が休みの日は旅行に出かけます。レジャー関係の服装のコーディネートはまかせてください。きっといい思い出ができますよ♪', birthday: '1985-12-10', age: '3０代', gender: '女', email: 'miki@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111114)
User.create(nickname: 'かんな', content: '彼氏の心を捕まえて離さない、ゆるふわコーデはできてますか？誰からも愛される可愛い女に慣れる着こなしを教えちゃいます！今日から違う自分を楽しみましょっ！！！', birthday: '1998-12-10', age: '２０代', gender: '女', email: 'kanna@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111115)
User.create(nickname: 'こうた', content: 'スーツは大事な仕事を支えます。着こなし次第で、契約が取れないなんてこともあるかも！？営業職の男性向けに、同じ営業の僕からアドバイスできると思います。', birthday: '1998-12-10', age: '２０代', gender: '男', email: 'kota@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111116)
User.create(nickname: 'あきお', content: '男の人生は４０代からです。毎日仕事場と会社の往復で疲れ切っていませんか？思い切って服装を変えることで人生がいい方向に開けるかも知れません。', birthday: '1973-12-10', age: '4０代', gender: '男', email: 'akio@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111117)
User.create(nickname: 'ゆうこ', content: '妹のコーディネートを考えるのが昔から好きでした。服は大好きで１００着以上持っています。ママ友からも服の相談によくのっています。皆さんに喜んでもらいたいです。', birthday: '1985-12-10', age: '3０代', gender: '女', email: 'yuko@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111118)
User.create(nickname: 'りか', content: '４０代の服装は２０代と同じでないほうがいいです。今更、どんな服装をしたらいいかわからないというあなたへ、元プロのスタイリストがアドバイスします。', birthday: '1973-12-10', age: '4０代', gender: '女', email: 'rika@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111119)
User.create(nickname: 'ただお', content: '大学生活を満喫したい人、集まれ！でも、毎日着ていく服を揃えるのが大変って人、集まれ！少ない服で着回しの達人の僕が、こっそり秘密を教えます。', birthday: '1998-12-10', age: '２０代', gender: '男', email: 'tadao@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: true, phone_number: 09011111110)
User.create(nickname: 'ももこ', content: '今度娘が結婚します。子供の結婚式は初めてなのでどういうものをきたらいいかさっぱりわかりません。相手の親御さんに引かれないような着こなしはありますか？', birthday: '1963-12-10', age: '5０代以上', gender: '女', email: 'momoko@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111121)
User.create(nickname: 'さとる', content: '友人と独立して会社を立ち上げる予定です。得意先周りに印象付けるために清潔感溢れる服装を心がけたいです。気取らず、誰でも親を持ってくれそうなスタイルはありますか？', birthday: '1985-12-10', age: '3０代', gender: '男', email: 'satoru@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111122)
User.create(nickname: 'ゆみ', content: '私はポッチャリ体型が昔からコンプレックスです。うまく体型を隠せるような服装がしたいと思っています。服装もだけど、アクセサリーなんかもアドバイスいただけると嬉しいです。', birthday: '1998-12-10', age: '２０代', gender: '女', email: 'yumi@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111123)
User.create(nickname: 'ゆうじ', content: 'メタボ体型が気になっています。来月転職活動を始めるので、心機一転、LEONに出てくるようなちょいわる親父を目指したいです。ブランドものを着てみたいですが、わかる方いらっしゃいますか？', birthday: '1973-12-10', age: '4０代', gender: '男', email: 'yuji@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111124)
User.create(nickname: 'ゆか', content: '今度旦那と映画を見に行きます。新婚時代に戻ったつもりで、ワンピースを着て行きたいです。主婦のため散財できません。手ごろな値段で良いお店はありますか？', birthday: '1985-12-10', age: '3０代', gender: '女', email: 'yuka@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111125)
User.create(nickname: 'かいと', content: '今年の秋に海外留学でアメリカに行きます。アメリカンなスタイルで海外を満喫したいので、コーディネートをよろしくお願いします。予算は１万円以内です。', birthday: '1998-12-10', age: '２０代', gender: '男', email: 'kaito@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111126)
User.create(nickname: 'れな', content: '年齢を重ねるたびに体型が変わってしまって、自分の思ったような服が着れません。今度同窓会があるのでそれなりの服をきて行きたいのですが、困っています。', birthday: '1963-12-10', age: '5０代以上', gender: '女', email: 'rena@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111127)
User.create(nickname: 'ゆうと', content: '彼女ができないので、少しでも自分を変えたいと思いジムに通い始めました。今ではジムが良いにハマってしまって、私服もスポーティにしたいがどうすればいいかわかりません。', birthday: '1998-12-10', age: '２０代', gender: '男', email: 'yuto@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111128)
User.create(nickname: 'さくら', content: '婚活に力を入れています。派手すぎず、かと言って地味すぎないクールで仕事ができる系のキャリアウーマンの着こなしを模索しています。', birthday: '1985-12-10', age: '3０代',  gender: '女', email: 'sakura@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111129)
User.create(nickname: 'あさこ', content: '私は幼稚園の先生をしています。毎日子供が相手なので可愛い服装ができません。でもお洒落は楽しみたいので、アドバイスお願いします。', birthday: '1998-12-10', age: '２０代', gender: '女', email: 'asako@gmail.com', password_digest: '000000', name: '相模健太郎', address: '新宿', adviser: false, phone_number: 09011111120)
